services:
  cloudflared:
    image: cloudflare/cloudflared:2026.1.2@sha256:e9bcb2ef08d25632ff74344e73a025f4f4bf12718335b196fa0e670cacace8c5
    container_name: cloudflared
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN={{ CF_TUNNEL_TOKEN }}
    networks:
      - proxy
    command: tunnel run
    volumes:
      - /home/scott/docker/cloudflared/config:/home/nonroot/.cloudflared/

networks:
  proxy:
    external: true
