services:
  cloudflared:
    image: cloudflare/cloudflared:2026.2.0@sha256:404528c1cd63c3eb882c257ae524919e4376115e6fe57befca8d603656a91a4c
    container_name: cloudflared
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN={{ CF_TUNNEL_TOKEN }}
    networks:
      - proxy
    command: tunnel run
    volumes:
      - /home/scott/docker/cloudflared/config:/home/nonroot/.cloudflared/

networks:
  proxy:
    external: true
