services:
  cloudflared:
    image: cloudflare/cloudflared:2026.1.1@sha256:5bb6a0870686742d00e171f36c892ba91e5994631bc363d808b9ba822262dad6
    container_name: cloudflared
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN={{ CF_TUNNEL_TOKEN }}
    networks:
      - proxy
    command: tunnel run
    volumes:
      - /home/scott/docker/cloudflared/config:/home/nonroot/.cloudflared/

networks:
  proxy:
    external: true
