---

admin_username: "scott"

timezone: "America/New_York"

pihole_upstream_dns_servers:
  - "127.0.0.1#5335"

bind_dns_listen_port: 5335
bind_dns_listen_address: 127.0.0.1

alloy_env_file_vars:
  CUSTOM_ARGS: "--server.http.listen-addr=0.0.0.0:12345 --disable-reporting"

chezmoi_dotfiles_repo: "https://github.com/bladewdr/dotfiles.git"

nagios_server_fqdn: "nagios.bladewdr.xyz"
nagios_allowed_hosts: "10.13.37.25"
nagios_hostgroups: servers

# Docker compose generator role
appdata_path: /apps
docker_compose_generator_output_path: /apps
docker_compose_generator_uid: 1000
docker_compose_generator_gid: 1000

