---

services:
  traefik:
    image: traefik:v3.6.7@sha256:2c5e029ee3638d3788b4ca7c8ef454baa8f924b91b190b3fd2742bee721ebeea
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 81:81
      - 443:443
      - 442:442
      - 8008:8008
    environment:
      - CF_API_EMAIL={{ CF_API_EMAIL }}
      - CF_DNS_API_TOKEN={{ CF_DNS_API_TOKEN }}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/data/traefik.yml:/traefik.yml:ro
      - ./traefik/data/acme.json:/acme.json
      - ./traefik/data:/config:ro
      - ./traefik/logs:/var/log/traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik-dashboard.{{ TRAEFIK_HOST_DOMAIN }}`)"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik-dashboard.{{ TRAEFIK_HOST_DOMAIN }}`)"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=zerossl"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main={{ TRAEFIK_HOST_DOMAIN }}"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.{{ TRAEFIK_HOST_DOMAIN }}"
      - "traefik.http.routers.traefik-secure.tls.domains[1].main={{ HOST_DOMAIN }}"
      - "traefik.http.routers.traefik-secure.tls.domains[1].sans=*.{{ HOST_DOMAIN }}"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.http.middlewares.authentik-proxy.forwardauth.address=http://authentik-proxy:9000/outpost.goauthentik.io/auth/traefik"
      - "traefik.http.middlewares.authentik-proxy.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.authentik-proxy.forwardauth.authResponseHeaders=X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version,X-Forwarded-User"

networks:
  proxy:
    external: true
