services:
  sablier:
    image: ghcr.io/sablierapp/sablier:1.11.0@sha256:3bd2c107b581cac4cea358d57c580d2fe298f2f860adccc281b83469b5e738f3
    container_name: ${SABLIER_CONTAINER_NAME:-sablier}
    restart: ${SABLIER_RESTART:-unless-stopped}
    networks:
      - proxy
    volumes:
      - /apps/sablier:/config
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ={{ host_timezone }}
    command:
      - start
      - --provider.name=docker
    labels:
      - traefik.enable=true
      - traefik.http.routers.sablier.entrypoints=https
      - traefik.http.routers.sablier.rule=Host(`sablier.{{ TRAEFIK_HOST_DOMAIN }}`)
      - traefik.http.services.sablier.loadbalancer.server.port=10000
      - traefik.http.middlewares.dynamic.plugin.sablier.group=sablier
      - traefik.http.middlewares.dynamic.plugin.sablier.dynamic.displayName=Sablier
      - traefik.http.middlewares.dynamic.plugin.sablier.dynamic.showDetails=true
      - traefik.http.middlewares.dynamic.plugin.sablier.sablierUrl=http://sablier:10000
      - traefik.http.middlewares.dynamic.plugin.sablier.sessionDuration=30m
      - traefik.http.middlewares.dynamic.plugin.sablier.ignoreUserAgent=curl
      - traefik.http.middlewares.dynamic.plugin.sablier.dynamic.theme=hacker-terminal
      - autoheal=true


networks:
  proxy:
    external: true
