services:
  postgres:
    image: postgres:18@sha256:38d5c9d522037d8bf0864c9068e4df2f8a60127c6489ab06f98fdeda535560f9
    restart: unless-stopped
    networks:
      - n8n_net
    environment:
      - POSTGRES_USER={{ n8n_postgres_user }}
      - POSTGRES_PASSWORD={{ n8n_postgres_password }}
      - POSTGRES_DB={{ n8n_postgres_db }}
      - POSTGRES_NON_ROOT_USER={{ n8n_postgres_normal_user }}
      - POSTGRES_NON_ROOT_PASSWORD={{ n8n_postgres_normal_user_password }}
    volumes:
      - /apps/n8n/db_storage:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U {{ n8n_postgres_user }} -d {{ n8n_postgres_db }}']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    image: docker.n8n.io/n8nio/n8n@sha256:aa499e07898e1599bd50ba07e967fc47cdc7fc78adb2430f588e0f8386b8ff39
    restart: unless-stopped
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE={{ n8n_postgres_db }}
      - DB_POSTGRESDB_USER={{ n8n_postgres_normal_user }}
      - DB_POSTGRESDB_PASSWORD={{ n8n_postgres_normal_user_password }}
      - N8N_GIT_NODE_DISABLE_BARE_REPOS=true
      - N8N_RUNNERS_ENABLED=true
    ports:
      - 5678:5678
    networks:
      - n8n_net
    links:
      - postgres
    volumes:
      - /apps/n8n/n8n_storage:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy

networks:
  n8n_net:

