---

services:
  server:
    image: docker.gitea.com/gitea:1.25.3
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - RUN_MODE=prod
      - DOMAIN=git.{{ APP0_HOST_DOMAIN }}
      - SSH_DOMAIN=git.{{ APP0_HOST_DOMAIN }}
      - HTTP_PORT=3000
      - ROOT_URL=https://git.{{ APP0_HOST_DOMAIN }}
      - SSH_PORT=222
      - DB_TYPE=sqlite3
      - DISABLE_REGISTRATION=true
    restart: unless-stopped
    ports:
      - 3000:3000
      - 222:22
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
