---
- name: Restart nagios
  when: not ansible_check_mode
  ansible.builtin.service:
    name: nagios
    state: restarted
  run_once: true
  delegate_to: "{{ nagios_server_fqdn }}"

- name: Restart nrpe
  when: not ansible_check_mode
  ansible.builtin.service:
    name: nagios-nrpe-server
    state: restarted
