services:
  fossflow:
    image: stnsmith/fossflow:master@sha256-46d43ead93b339317338c1e74b04c38764238a715980f503c569690891a25990
    restart: unless-stopped
    container_name: fossflow
    ports:
      - "3000:3000"
    environment:
      - PUBLIC_URL=/
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://127.0.0.1:3000 || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
