services:
  fossflow:
    image: stnsmith/fossflow:master@sha256:9a926810912701b4271cbf02272c9c499e35e1371a6819afe8f9fb8a56c13daa
    restart: unless-stopped
    container_name: fossflow
    ports:
      - "3000:3000"
    environment:
      - PUBLIC_URL=/
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://127.0.0.1:3000 || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
