services:
  fossflow:
    image: stnsmith/fossflow:master@sha256:891e3b2296e5cf3ee8d319ea0d6b8ea03597323b4a61cbba5d98259f13a108c5
    restart: unless-stopped
    container_name: fossflow
    ports:
      - "3000:3000"
    environment:
      - PUBLIC_URL=/
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://127.0.0.1:3000 || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
