---

services:
  postgresql:
    image: docker.io/library/postgres:16-alpine@sha256:4327b9fd295502f326f44153a1045a7170ddbfffed1c3829798328556cfd09e2
    container_name: authentik-postgresql
    restart: unless-stopped
    networks:
      - proxy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d authentik -U authentik"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - ./authentik/database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: {{ AUTHENTIK_PG_PASS }}
      POSTGRES_USER: authentik
      POSTGRES_DB: authentik
  server:
    image: ghcr.io/goauthentik/server:2025.12.1@sha256:94e25e04a05cfbb2450803e7782b8d1297b5c898df43b28a7fd6e47fe276301c
    container_name: authentik-server
    restart: unless-stopped
    ports:
      - 9000:9000
      - 19443:9443
    command: server
    networks:
      - proxy
    environment:
      #AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: {{ AUTHENTIK_PG_PASS }}
      AUTHENTIK_EMAIL__HOST: {{ SMTP_SERVER_ADDRESS }}
      AUTHENTIK_EMAIL__PORT: 465
      AUTHENTIK_SECRET_KEY: {{ AUTHENTIK_SECRET }}
      AUTHENTIK_TOKEN: {{ AUTHENTIK_TOKEN }}
      # Optionally authenticate (don't add quotation marks to your password)
      AUTHENTIK_EMAIL__USERNAME: {{ SMTP_USERNAME }}
      AUTHENTIK_EMAIL__PASSWORD: {{ AUTHENTIK_SMTP_PASSWORD }}
      # Use StartTLS
      AUTHENTIK_EMAIL__USE_TLS: false
      # Use SSL
      AUTHENTIK_EMAIL__USE_SSL: true
      AUTHENTIK_EMAIL__TIMEOUT: 10
      # Email address authentik will send from, should have a correct @domain
      AUTHENTIK_EMAIL__FROM: {{ SMTP_FROM }}
    labels:
      - traefik.enable=true
      - traefik.http.routers.authentik.entrypoints=https
      - traefik.http.routers.authentik.rule=Host(`{{ AUTHENTIK_HOST }}`)
      - traefik.http.routers.authentik.service=authentik
      - traefik.http.services.authentik.loadbalancer.server.scheme=http
      - traefik.http.services.authentik.loadbalancer.server.port=9000
      - traefik.http.routers.authentik.tls=true
    volumes:
      - ./authentik/media:/media
      - ./authentik/custom-templates:/templates
    depends_on:
      postgresql:
        condition: service_healthy
  worker:
    image: ghcr.io/goauthentik/server:2025.12.1@sha256:94e25e04a05cfbb2450803e7782b8d1297b5c898df43b28a7fd6e47fe276301c
    container_name: authentik-worker
    restart: unless-stopped
    command: worker
    networks:
      - proxy
    environment:
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: {{ AUTHENTIK_PG_PASS }}
      AUTHENTIK_EMAIL__HOST: {{ SMTP_SERVER_ADDRESS }}
      AUTHENTIK_EMAIL__PORT: 465
      # Optionally authenticate (don't add quotation marks to your password)
      AUTHENTIK_EMAIL__USERNAME: {{ SMTP_USERNAME }}
      AUTHENTIK_EMAIL__PASSWORD: {{ AUTHENTIK_SMTP_PASSWORD }}
      # Use StartTLS
      AUTHENTIK_EMAIL__USE_TLS: false
      # Use SSL
      AUTHENTIK_EMAIL__USE_SSL: true
      AUTHENTIK_EMAIL__TIMEOUT: 10
      # Email address authentik will send from, should have a correct @domain
      AUTHENTIK_EMAIL__FROM: {{ SMTP_FROM }}
      AUTHENTIK_SECRET_KEY: {{ AUTHENTIK_SECRET }}
      AUTHENTIK_TOKEN: {{ AUTHENTIK_TOKEN }}
    # `user: root` and the docker socket volume are optional.
    # See more for the docker socket integration here:
    # https://goauthentik.io/docs/outposts/integrations/docker
    # Removing `user: root` also prevents the worker from fixing the permissions
    # on the mounted folders, so when removing this make sure the folders have the correct UID/GID
    # (1000:1000 by default)
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./authentik/media:/media
      - ./authentik/certs:/certs
      - ./authentik/custom-templates:/templates
    depends_on:
      - postgresql

  authentik-proxy:
    image: ghcr.io/goauthentik/proxy:2025.12.1@sha256:05d08f10759ece45acf498bd09ce99f3bb8a36cd69aaac10d601cbc35c4f47aa
    container_name: authentik-proxy
    networks:
      - proxy
    depends_on:
      server:
        condition: service_started
      postgresql:
        condition: service_healthy
    environment:
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: {{ AUTHENTIK_PG_PASS }}
      AUTHENTIK_HOST: http://authentik-server:9000
      AUTHENTIK_INSECURE: "true"
      AUTHENTIK_TOKEN: {{ AUTHENTIK_TOKEN }}
      AUTHENTIK_HOST_BROWSER: https://{{ AUTHENTIK_HOST }}
      AUTHENTIK_DEBUG: true
      POSTGRES_PASSWORD: {{ AUTHENTIK_PG_PASS }}
    labels:
      traefik.enable: true
      traefik.port: 9000
      traefik.http.routers.authentik-proxy.entrypoints: https
      traefik.http.routers.authentik-proxy.rule: HostRegexp(`{{ FRESHRSS_URL }}`) && PathPrefix(`/outpost.goauthentik.io/`)
    restart: unless-stopped

networks:
  proxy:
    external: true
