networks:
  proxy:
    external: true
  flare-db:

services:
  flare:
      container_name: flare
      restart: unless-stopped
      networks:
        - proxy
        - flare-db
      environment:
        - NEXTAUTH_URL={{ FLARE_NEXTAUTH_URL }}
        - NEXTAUTH_SECRET={{ FLARE_NEXTAUTH_SECRET }}
        - DATABASE_URL={{ FLARE_DATABASE_URL }}
      volumes:
        - ./flare/uploads:/app/uploads
      labels:
        - traefik.enable=true
        - traefik.http.routers.flare.rule=Host(`{{ FLARE_HOST }}`)
        - traefik.http.routers.flare.service=flare
        - traefik.http.routers.flare.tls=true
        - traefik.http.middlewares.flare=default-headers@file
        - traefik.http.middlewares.flare=https-redirectscheme@file
        - traefik.http.routers.flare.middlewares=default-headers@file
        - traefik.http.services.flare.loadbalancer.server.port=3000
        - traefik.docker.network=proxy
      image: flintsh/flare:1.6.1@sha256:1245201dea7fc779b1fa04373d57b048c6c49bb0341683d66a85148d4a38630b
      depends_on:
        postgres:
          condition: service_healthy
  postgres:
      image: postgres:16-alpine@sha256:23e88eb049fd5d54894d70100df61d38a49ed97909263f79d4ff4c30a5d5fca2
      restart: unless-stopped
      networks:
        - flare-db
      container_name: flare-db
      environment:
        - POSTGRES_USER=flare
        - POSTGRES_PASSWORD={{ FLARE_POSTGRES_PW }}
        - POSTGRES_DB=flare
      ports:
        - "5432:5432"
      volumes:
        - ./flare/database:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -h localhost -U flare -d flare"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 20s
