---
services:
  hypermind:
    container_name: hypermind
    network_mode: host
    restart: unless-stopped
    environment:
      - PORT=9996
    image: ghcr.io/lklynet/hypermind:latest@sha256:74b7a0335214fea872c578fcf2f04432fd5b29c5340fadcae2e2572a5a611959
