---
volumes:
  kiwix-data:
    labels:
      - remove_volume_on=down
    driver_opts:
      type: nfs
      o: "addr=nas01.bladewdr.xyz,nolock,noatime,soft,rw"
      device: ":/mnt/tank/kiwix"

networks:
  proxy:
    external: true

services:
  kiwix-serve:
    container_name: kiwix
    image: ghcr.io/kiwix/kiwix-serve:3.8.1@sha256:9bffd4f940645d4d518f137e87b7865d3d0ef30f6c13fbe4a3b9e747be3cd1ad
    networks:
      - proxy
    volumes:
      - kiwix-data:/data
    command:
      - '*.zim'
