---
volumes:
  kiwix-data:
    labels:
      - remove_volume_on=down
    driver_opts:
      type: nfs
      o: "addr=nas01.bladewdr.xyz,nolock,noatime,soft,rw"
      device: ":/mnt/tank/kiwix"

networks:
  proxy:
    external: true

services:
  kiwix-serve:
    container_name: kiwix
    image: ghcr.io/kiwix/kiwix-serve:3.8.0@sha256:6e3eece55aadd72dd359c4368cd36638787f4e3fe095acbd61ef8ddede5422c3
    networks:
      - proxy
    volumes:
      - kiwix-data:/data
    command:
      - '*.zim'
