---

- name: restart timesyncd
  ansible.builtin.service:
    name: systemd-timesyncd
    state: restarted

- name: restart-ssh
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: enable and start guest agent
  ansible.builtin.service:
    name: qemu-guest-agent
    state: started
    enabled: true
