---
- name: Nagios installation tasks.
  when: "nagios_server_fqdn == inventory_hostname"
  block:
    - name: Install Nagios dependencies.
      ansible.builtin.apt:
        name: "{{ nagios_dependencies }}"
        update_cache: true
        cache_valid_time: 3600

    - name: Add system admin user to the nagios group.
      ansible.builtin.user:
        name: "{{ admin_username }}"
        groups: nagios
        append: true
      when: not ansible_check_mode

    - name: Copy over custom-commands.cfg
      ansible.builtin.copy:
        src: custom-commands.cfg
        dest: /usr/local/nagios/etc/objects/custom-commands.cfg
        owner: nagios
        group: nagios
        mode: '0664'
      notify: Restart nagios

    - name: Copy over hostgroups.cfg
      ansible.builtin.copy:
        src: host_templates/hostgroups.cfg
        dest: /usr/local/nagios/etc/objects/hostgroups.cfg
        owner: nagios
        group: nagios
        mode: '0664'
      notify: Restart nagios
