services:
  bobbeh_bot:
    build: https://github.com/BladeWDR/bobbeh_bot.git
    container_name: bobbeh_bot
    env_file:
      - bobbeh.env
    volumes:
      - ./bobbeh_bot/config.yml:/opt/bobbeh_bot/config.yml:ro
    restart: unless-stopped
