---
services:
  nginx:
    container_name: mkdocs-nginx
    image: nginx@sha256:341bf0f3ce6c5277d6002cf6e1fb0319fa4252add24ab6a0e262e0056d313208
    volumes:
      - ./mkdocs-wiki/html:/usr/share/nginx/html:ro
    networks:
      - proxy
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.mkdocs-nginx.rule=Host(`wiki.{{ TRAEFIK_HOST_DOMAIN }}`)
      - traefik.http.routers.mkdocs-nginx.service=wiki
      - traefik.http.routers.mkdocs-nginx.tls=true
      - traefik.http.middlewares.mkdocs-nginx=default-headers@file
      - traefik.http.middlewares.mkdocs-nginx=https-redirectscheme@file
      - traefik.http.routers.mkdocs-nginx.middlewares=default-headers@file
      - traefik.http.services.wiki.loadbalancer.server.port=80
      - traefik.docker.network=proxy

networks:
  proxy:
    external: true
