---
services:
  nginx:
    container_name: mkdocs-nginx
    image: nginx@sha256:fb01117203ff38c2f9af91db1a7409459182a37c87cced5cb442d1d8fcc66d19
    volumes:
      - ./mkdocs-wiki/html:/usr/share/nginx/html:ro
    networks:
      - proxy
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.mkdocs-nginx.rule=Host(`wiki.{{ TRAEFIK_HOST_DOMAIN }}`)
      - traefik.http.routers.mkdocs-nginx.service=wiki
      - traefik.http.routers.mkdocs-nginx.tls=true
      - traefik.http.middlewares.mkdocs-nginx=default-headers@file
      - traefik.http.middlewares.mkdocs-nginx=https-redirectscheme@file
      - traefik.http.routers.mkdocs-nginx.middlewares=default-headers@file
      - traefik.http.services.wiki.loadbalancer.server.port=80
      - traefik.docker.network=proxy

networks:
  proxy:
    external: true
