services:
  joyride:
    image: ghcr.io/traefikturkey/joyride:${JOYRIDE_DOCKER_TAG:-latest}
    container_name: ${JOYRIDE_CONTAINER_NAME:-joyride}
    restart: ${JOYRIDE_RESTART:-unless-stopped}
    mem_limit: ${JOYRIDE_MEM_LIMIT:-100m}
    environment:
      - TZ=${TZ}
      - HOSTIP=${HOSTIP}
      - JOYRIDE_NXDOMAIN_ENABLED=${JOYRIDE_NXDOMAIN_ENABLED:-false}
      - JOYRIDE_LOG_DEBUG=${JOYRIDE_LOG_DEBUG:-false}
      - JOYRIDE_LOG_QUERIES=${JOYRIDE_LOG_QUERIES:-false}
      - JOYRIDE_ENABLE_SERF=${JOYRIDE_ENABLE_SERF:-false}
    network_mode: host
    # ports:
    #   - ${JOYRIDE_PORT:-54}:54/udp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /apps/joyride/hosts.d:/etc/hosts.d:ro
    labels:
      - traefik.enable=${JOYRIDE_TRAEFIK_ENABLE:-false}
      - autoheal=${JOYRIDE_AUTOHEAL:-true}
