networks:
  proxy:
    external: true

services:
  mailrise:
    image: yoryan/mailrise
    container_name: mailrise
    volumes:
       - ./mailrise/mailrise.conf:/etc/mailrise.conf:ro
    ports:
       - 8025:8025
    networks:
       - proxy
    restart: unless-stopped
