---
collections:
  - name: grafana.grafana
  - name: community.general

roles:
  - name: geerlingguy.docker
  - name: ansible-role-starship
    src: https://github.com/bladewdr/ansible-role-starship.git
    scm: git
    version: main
