---

services:
    fivefilters-full-text-rss:
        container_name: fullrss
        ports:
            - '50000:80'
        restart: unless-stopped
        volumes:
            - "./fullrss/rss-cache:/var/www/html/cache"
        image: 'heussd/fivefilters-full-text-rss:latest'
        environment:
            - FTR_ADMIN_PASSWORD={{ FFR_PASSWORD }}
        labels:
            - traefik.enable=true
            - traefik.http.routers.fullrss.rule=Host(`ffr.{{ TRAEFIK_HOST_DOMAIN }}`)
            - traefik.http.routers.fullrss.entrypoints=https
            - traefik.http.routers.fullrss.middlewares=default-headers@file,https-redirectscheme@file
            - traefik.http.routers.fullrss.tls=true
            - traefik.http.routers.fullrss.service=fullrss
            - traefik.http.services.fullrss.loadbalancer.server.port=80
        networks:
            - proxy

networks:
  proxy:
    external: true

