---

- name: Install Apache.
  ansible.builtin.apt:
    name: apache2
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Enable apache service.
  ansible.builtin.service:
    name: apache2
    enabled: true
